name: Turbo Cache
description: Persist Turbo cache

inputs:
outputs:

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

