name: Docs
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn turbo build --filter=@material-solid/docs...

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: apps/docs/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: cloudflare-pages
      cancel-in-progress: true
    environment:
      name: cloudflare-pages
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: docs
          path: dist
      - id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=material-solid --commit-dirty=true
          packageManager: yarn
