name: Docs
on:
  push:
    branches: [main]
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn workspaces focus @material-solid/docs
      - run: yarn :docs build
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: apps/docs/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: cloudflare-pages
      cancel-in-progress: true
    environment:
      name: cloudflare-pages
      url: ${{ steps.deploy.outputs.deployment-url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: apps/docs/dist
      - id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/docs/dist --project-name=material-solid --commit-dirty=true
