name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
      - run: yarn install
      - run: yarn turbo build --filter=@material-solid/components...

      - uses: actions/upload-artifact@v4
        with:
          name: components
          path: |
            packages/components/dist/
            packages/vanilla-extract/dist/
            packages/utils/dist/
