name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          registry-url: https://npm.pkg.github.com
          # registry-url: https://registry.npmjs.org
          scope: "@material-solid"
      - run: yarn install
      - run: yarn turbo build --filter=@material-solid/components...
      - run: "yarn : @material-solid/components npm publish"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
