name: Vercel Preview
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: vercel-preview
      url: ${{ steps.deploy.outputs.VERCEL_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: "yarn workspaces focus @material-solid/docs-next"

      - name: Pull Vercel environment information
        run: "yarn : @material-solid/docs-next vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}"

      - name: Build
        run: "yarn : @material-solid/docs-next vercel build --token=${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy to Vercel
        id: deploy
        run: |
          yarn : @material-solid/docs-next vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > vercel-url.txt
          echo "VERCEL_URL=$(cat vercel-url.txt) >> "$GITHUB_OUTPUT"
